import type { FooterProps, ProductListItem } from "@yami/design-system";
import {
  createFooterAppLinks,
  createFooterColumns,
  createFooterLegalLinks,
  createFooterPaymentMarks,
  createFooterSocialLinks,
  footerCopy,
} from "@yami/design-system/components/Footer/fixtures";

import { createStorefrontHeader } from "../storefront-header.fixture";

import type { ProductDetailPageProps } from "./ProductDetailPage.types";

export type ProductDetailPageLocale = "zh" | "en";

const koreaRegionIcon = new URL(
  "../../../design-system/components/Header/assets/korea.png",
  import.meta.url
).href;

const productImages = [
  ["front", "22f1eabda8bc0200d050ebcb1ebdb469", "Torriden Dive In Low Molecule Hyaluronic Acid Mask box, front view"],
  ["packaging", "c635ba73e529d262e7b2e25d3a7fb89c", "Torriden Dive In mask packaging and individual sheet"],
  ["sheet", "f743668cac11a24b973ff93050844c06", "Torriden Dive In sheet mask texture detail"],
  ["benefits", "1923d15747c92c8d0654f5fa2126e8a0", "Torriden Dive In mask hydration benefits"],
  ["essence", "1e27d193f4e6419c5022dbcdb7cb6999", "Torriden Dive In mask essence and skin application"],
  ["routine", "40b6a28e72b49612936923948ae7953e", "Torriden Dive In mask skincare routine detail"],
] as const;

function image(hash: string) {
  return `https://cdn.yamibuy.net/item/${hash}_757x757.webp`;
}

function recommendation(
  id: string,
  hash: string,
  brand: string,
  title: string,
  priceCurrent: string,
  priceOriginal: string,
  ratingCount: string,
): ProductListItem {
  return {
    id,
    href: `#${id}`,
    image: image(hash),
    imageAlt: title,
    brand,
    brandHref: `#${brand.toLowerCase()}`,
    title,
    priceCurrent,
    priceOriginal,
    rating: 4.8,
    ratingCount,
    soldCount: "100+ sold",
    badges: [{ label: "Low Price", type: "low-price" }],
    addButtonAriaLabel: `Add ${title} to cart`,
  };
}

const recentlyViewedProducts: ProductListItem[] = [
  {
    id: "recent-elegance-face-powder",
    href: "#recent-elegance-face-powder",
    image:
      "https://cdn.yamibuy.net/item/ebde4aedd980a725501d9ed711255d2a_300x300.webp",
    imageAlt: "ELEGANCE Face Powder Compact #I",
    brand: "ELEGANCE",
    brandHref: "#elegance",
    title: "Face Powder Compact #I, 0.31 oz @Cosme Award",
    ranking: "#6 Top Reordered Foundation, Concealer, Setting",
    rating: 4.9,
    ratingCount: "15",
    soldCount: "60+ Sold",
    priceCurrent: "$119.99",
    priceOriginal: "$144.99",
    addButtonAriaLabel: "Add ELEGANCE Face Powder Compact #I to cart",
  },
  {
    id: "recent-skin1004-sun-serum",
    href: "#recent-skin1004-sun-serum",
    image:
      "https://cdn.yamibuy.net/item/ae08094e7ec81daa6dccb333ee8e4b4e_300x300.webp",
    imageAlt: "SKIN1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum value pack",
    brand: "SKIN1004",
    brandHref: "#skin1004",
    title:
      "Madagascar Centella Hyalu-Cica Water-Fit Sun Serum, Brightening, 1.69 fl oz.*2 Dry&Sensitive Skin【Value Pack】",
    rating: 5,
    ratingCount: "4",
    soldCount: "100+ Sold",
    priceCurrent: "$24.29",
    priceOriginal: "$34.99",
    badges: [
      { label: "Choice", type: "choice" },
      { label: "-30%", type: "discount" },
    ],
    addButtonAriaLabel: "Add SKIN1004 sun serum value pack to cart",
  },
  {
    id: "recent-beplain-cleanser",
    href: "#recent-beplain-cleanser",
    image:
      "https://cdn.yamibuy.net/item/29aad4f8b0c444171882b043ca849b08_300x300.webp",
    imageAlt: "beplain Mung Bean ph-Balanced Cleansing Foam",
    brand: "beplain",
    brandHref: "#beplain",
    title: "Mung Bean ph-Balanced Cleansing Foam, 5.41 fl oz",
    ranking: "#9 Best Sellers in Cleanser & Exfoliators",
    rating: 4.7,
    ratingCount: "3",
    soldCount: "70+ Sold",
    priceCurrent: "$18.99",
    priceOriginal: "$26.00",
    badges: [{ label: "-26%", type: "discount" }],
    addButtonAriaLabel: "Add beplain Mung Bean Cleansing Foam to cart",
  },
  {
    id: "recent-beauty-of-joseon-sun",
    href: "#recent-beauty-of-joseon-sun",
    image:
      "https://cdn.yamibuy.net/item/0a5b71afa1d59b2f45ce0a5b90a3b4f2_300x300.webp",
    imageAlt: "Beauty of Joseon Relief Sun Rice Probiotics value pack",
    brand: "Beauty of Joseon",
    brandHref: "#beauty-of-joseon",
    title:
      "Relief Sun Rice Probiotics Sunscreen SPF50+·PA++++, 1.7 fl oz*2【Value Pack】",
    rating: 5,
    ratingCount: "7",
    soldCount: "200+ Sold",
    priceCurrent: "$22.59",
    priceOriginal: "$39.98",
    badges: [
      { label: "Choice", type: "choice" },
      { label: "Low Price", type: "low-price" },
    ],
    addButtonAriaLabel: "Add Beauty of Joseon Relief Sun value pack to cart",
  },
  {
    id: "recent-marukyu-matcha",
    href: "#recent-marukyu-matcha",
    image:
      "https://cdn.yamibuy.net/item/e3c1f9f0a0fa194ebba0e3c6aa34928e_300x300.webp",
    imageAlt: "MARUKYU KOYAMAEN Japanese Matcha Powder Wakatake",
    brand: "MARUKYU KOYAMAEN",
    brandHref: "#marukyu-koyamaen",
    title:
      "Japanese Matcha Powder Wakatake, 3.53 oz【Fresh Green Tea Aroma】【For Drinks & Cooking】",
    soldCount: "60+ Sold",
    priceCurrent: "$42.99",
    priceOriginal: "$69.99",
    badges: [{ label: "Low Price", type: "low-price" }],
    addButtonAriaLabel: "Add MARUKYU KOYAMAEN Matcha Powder Wakatake to cart",
  },
  {
    id: "recent-sk-ii-essence",
    href: "#recent-sk-ii-essence",
    image:
      "https://cdn.yamibuy.net/item/b21c446891140d6f29c77841b085fd28_300x300.webp",
    imageAlt: "SK-II Facial Treatment Essence",
    brand: "SK-II",
    brandHref: "#sk-ii",
    title: "SK-II Facial Treatment Essence, 330 ml / 11 oz",
    priceCurrent: "$339.00",
    addButtonAriaLabel: "Add SK-II Facial Treatment Essence to cart",
  },
  {
    id: "recent-anua-cleanser",
    href: "#recent-anua-cleanser",
    image:
      "https://cdn.yamibuy.net/item/3ea01df0ad0bb3f01a8de350a241c9ba_300x300.webp",
    imageAlt: "ANUA 8 Hyaluronic Acid Hydrating Gentle Foaming Cleanser",
    brand: "ANUA",
    brandHref: "#anua",
    title: "8 Hyaluronic Acid Hydrating Gentle Foaming Cleanser, 5.07 fl oz",
    rating: 5,
    ratingCount: "1",
    soldCount: "30+ Sold",
    priceCurrent: "$11.52",
    priceOriginal: "$13.99",
    badges: [{ label: "Low Price", type: "low-price" }],
    addButtonAriaLabel: "Add ANUA 8 Hyaluronic Acid Cleanser to cart",
  },
  {
    id: "recent-anua-cleansing-oil",
    href: "#recent-anua-cleansing-oil",
    image:
      "https://cdn.yamibuy.net/item/780e2ce08cddc33308de249579d7fced_300x300.webp",
    imageAlt: "ANUA Heartleaf Pore Control Cleansing Oil",
    brand: "ANUA",
    brandHref: "#anua",
    title:
      "Heartleaf Pore Control Cleansing Oil, 6.76 fl oz, Quick Makeup Removal",
    ranking: "#6 Most Liked Makeup Remover",
    soldCount: "80+ Sold",
    priceCurrent: "$18.99",
    priceOriginal: "$19.99",
    addButtonAriaLabel: "Add ANUA Heartleaf Pore Control Cleansing Oil to cart",
  },
];

function createFooter(locale: ProductDetailPageLocale): FooterProps {
  const copy = footerCopy[locale];
  return {
    ariaLabel: copy.ariaLabel,
    columns: createFooterColumns(locale),
    socialLinks: createFooterSocialLinks(locale),
    subscribe: {
      title: copy.subscribeTitle,
      label: copy.subscribeLabel,
      placeholder: copy.subscribePlaceholder,
      submitLabel: copy.subscribeSubmit,
    },
    appTitle: copy.appTitle,
    appLinks: createFooterAppLinks(),
    copyright: copy.copyright,
    legalLinks: createFooterLegalLinks(locale),
    paymentMarks: createFooterPaymentMarks(),
    imageLoading: "lazy",
  };
}

function createProductDetailHeader(locale: ProductDetailPageLocale) {
  const header = createStorefrontHeader(locale);
  return {
    ...header,
    mobileVariant: "pdp" as const,
    imageLoadingStrategy: "windowed" as const,
  };
}

export function createProductDetailPageFixture(
  locale: ProductDetailPageLocale = "en",
): ProductDetailPageProps {
  const fixture: ProductDetailPageProps = {
    lang: locale,
    contentMaxWidth: 1920,
    header: createProductDetailHeader(locale),
    footer: createFooter(locale),
    breadcrumb: [
      { label: "Beauty", href: "#beauty" },
      { label: "Masks", href: "#masks" },
      { label: "Sheet Masks" },
    ],
    images: productImages.map(([id, hash, alt], index) => ({
      id,
      src: image(hash),
      alt,
      ...(index === productImages.length - 1 ? {
        thumbnailPinned: true,
        thumbnailOverlayLabel: "Skin Info",
      } : {}),
    })),
    brand: "Torriden",
    brandHref: "#torriden",
    title: "Dive In Low Molecule Hyaluronic Acid Mask, 0.91 fl oz 10pcs",
    ranking: "#3 Most Liked Masks",
    rating: 4.7,
    ratingCount: "10",
    soldCount: "400+ sold this week",
    priceCurrent: "$16.29",
    priceOriginal: "$20.99",
    discountLabel: "22% off",
    optionGroups: [
      {
        id: "mask-type",
        label: "Mask Type",
        value: "hyaluronic",
        options: [
          { label: "Pink Cellmazing Firming", value: "firming" },
          { label: "Hyaluronic", value: "hyaluronic" },
          { label: "Cica", value: "cica" },
        ],
      },
      {
        id: "packaging",
        label: "Standard Packaging",
        value: "10-sheets",
        options: [
          { label: "4 sheets/box", value: "4-sheets" },
          { label: "5 sheets", value: "5-sheets" },
          { label: "10 sheets", value: "10-sheets" },
          { label: "20 sheets", value: "20-sheets" },
          { label: "3 packs", value: "3-packs" },
        ],
      },
    ],
    // Demo inventory, not live stock: firming is available only in 5 sheets;
    // 3 packs is sold out for every mask type.
    skus: ["firming", "hyaluronic", "cica"].flatMap((type) =>
      ["4-sheets", "5-sheets", "10-sheets", "20-sheets", "3-packs"].map((packaging) => ({
        options: { "mask-type": type, packaging },
        available: packaging !== "3-packs" && (type !== "firming" || packaging === "5-sheets"),
      }))
    ),
    bestBefore: "Sep 15, 2028",
    highlights: [
      "Contains a 5D hyaluronic acid complex designed for multi-layer hydration.",
      "Soft vegan cellulose sheets hold a full bottle of essence and conform closely to skin.",
      "The lightweight essence absorbs without a sticky finish, including on oily skin.",
      "Soothing ingredients support sensitive skin and help reduce post-use tightness.",
      "A 15-minute routine leaves skin feeling supple, dewy, and comfortably hydrated.",
    ],
    specifications: [
      { label: "Brand", value: "Torriden" },
      { label: "Brand origin", value: "Korea" },
      { label: "Net content", value: "1 box" },
      { label: "Mask type", value: "Hyaluronic" },
      { label: "Packaging", value: "10 sheets" },
    ],
    serviceDetailsHref: "#product-highlights",
    purchaseTags: ["Best Sellers", "New Arrivals", "Dryness", "Oily", "Dry"],
    region: {
      label: "Region",
      value: "Korea",
      iconSrc: koreaRegionIcon,
    },
    recommendations: [
      recommendation("biodance-mask", "c8dcfa16d92b0def7c96453886efa36e", "BIODANCE", "Bio-Collagen Real Deep Mask, Hydrating and Firming, 4pcs", "$16.00", "$19.00", "41"),
      recommendation("mediheal-mask", "868c0f52ce4313e6e25590c6912b76be", "MEDIHEAL", "Essential Mask Madecassoside Soothing, 10 sheets", "$10.39", "$26.99", "22"),
      recommendation("abib-mask", "090012ed3cd043cc3ee4ed514a5d56a9", "Abib", "Mild Acidic pH Sheet Mask, 10 sheets", "$16.29", "$19.99", "18"),
      recommendation("torriden-cica", "571149d4d5b62b680da7db7c4cf4da19", "Torriden", "Balanceful Cica Mask, Soothing Care, 10 sheets", "$17.49", "$29.99", "12"),
      recommendation("jm-solution-mask", "676f94362d286f3b93d0d1dee0b31cb2", "JMsolution", "Active Jellyfish Vital Mask Prime, 10 sheets", "$8.09", "$17.50", "219"),
      recommendation("abib-glutathiosome-mask", "73b46a19a95b9d0ef8dc5f51f8e88d36", "Abib", "Mild Acidic pH Sheet Mask, Glutathiosome fit, 10 sheets/box", "$15.89", "$19.66", "70"),
      recommendation("dr-jart-vital-hydra-mask", "8b494fb3edce1e9f6a9ec9fa21e9bc1f", "Dr.Jart+", "Vital Hydra Solution Face Mask, 5 sheets/box × 3", "$19.99", "$35.97", "596"),
      recommendation("snp-birds-nest-mask", "fd8182dd56284740b83a16dcd23cbeeb", "SNP", "Bird’s Nest Aqua Ampoule Mask, 10 sheets", "$8.09", "$17.50", "219"),
    ],
    reviewSection: {
      title: "Customer Reviews",
      reviewCount: 10,
      averageRating: 4.7,
      ratingDistribution: [
        { stars: 5, percentage: 80, count: 8 },
        { stars: 4, percentage: 10, count: 1 },
        { stars: 3, percentage: 10, count: 1 },
        { stars: 2, percentage: 0, count: 0 },
        { stars: 1, percentage: 0, count: 0 },
      ],
      reviews: [
        {
          id: "review-k-baby",
          rating: 5,
          reviewer: "K Baby",
          reviewedAt: "Dec 8, 2024",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Very hydrating and comfortable to use.",
          showOriginalHref: "#review-k-baby-original",
          helpfulCount: 2,
          commentCount: 0,
        },
        {
          id: "review-rain",
          rating: 5,
          reviewer: "Rain***",
          reviewedAt: "Mar 13, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A deeply moisturizing mask that leaves skin feeling soft.",
          showOriginalHref: "#review-rain-original",
          helpfulCount: 1,
          commentCount: 0,
        },
        {
          id: "review-daren",
          rating: 5,
          reviewer: "Daren***",
          reviewedAt: "Aug 3, 2026",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Noticeably moisturizing and comfortable to apply.",
          helpfulCount: 0,
          commentCount: 0,
          photos: [
            {
              src: image("f743668cac11a24b973ff93050844c06"),
              alt: "Torriden sheet mask texture shared with a review",
            },
          ],
        },
        {
          id: "review-sammi",
          rating: 5,
          reviewer: "SammiG107",
          reviewedAt: "Dec 22, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "My skin felt more moisturized after use, and I would purchase it again.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-meencantachina",
          rating: 5,
          reviewer: "Meencantachina",
          reviewedAt: "Aug 24, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A simple routine with a strong hydrating effect.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-mujimuji",
          rating: 4,
          reviewer: "mujimuji",
          reviewedAt: "Mar 29, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Hydrating for dry, sensitive skin with a lightweight finish.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-dorothy",
          rating: 3,
          reviewer: "dorothyhaz",
          reviewedAt: "Sep 25, 2024",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A pleasant mask with a soft sheet and comfortable essence.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-tasha",
          rating: 5,
          reviewer: "tasha奶奶",
          reviewedAt: "Aug 13, 2022",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "The sheet feels substantial and leaves skin moisturized without heaviness.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-biubiu",
          rating: 5,
          reviewer: "BiubiuJose",
          reviewedAt: "Jan 12, 2026",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A convenient moisturizing step with a comfortable, non-sticky finish.",
          helpfulCount: 3,
          commentCount: 0,
        },
        {
          id: "review-sky",
          rating: 5,
          reviewer: "skincarelover",
          reviewedAt: "Apr 7, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Soft, soothing, and easy to fit into a weekly hydration routine.",
          helpfulCount: 1,
          commentCount: 0,
        },
      ],
      copy: {
        reviewsLabel: "Reviews",
        referenceNotice:
          "Some reviews are from other options and are shown for reference.",
        writeReview: "Write a review",
        all: "All",
        purchased: "Purchased",
        photos: "Photos",
        reviewPhotos: "Review Photos",
        sortBy: "Sort by",
        viewMore: "View All Reviews",
        verifiedPurchase: "Verified purchase",
        currentItem: "Current item",
        showOriginal: "Show original",
        helpful: "Helpful",
        comments: "Comments",
        noReviews: "No reviews match this filter.",
        stars: "Stars",
        resetFilter: "Show all reviews",
      },
      sortOptions: [
        { value: "default", label: "Default" },
        {
          value: "recent",
          label: "Most recent",
          compare: (left, right) =>
            Date.parse(String(right.reviewedAt ?? "")) -
            Date.parse(String(left.reviewedAt ?? "")),
        },
      ],
      initialVisibleCount: 6,
      viewMoreIncrement: 4,
    },
    brandSection: {
      title: "Torriden",
      titleLang: "en",
      logo: {
        src: "https://cdn.yamibuy.net/brand/792b967e8361282011110f2387764792_240x120.webp",
        width: 120,
        height: 60,
      },
      aboutLabel: "About the brand",
      description:
        "Torriden creates clean, vegan, and cruelty-free formulas focused on effective hydration. Its signature 5D-Complex low molecular hyaluronic acid supports layered moisture without a sticky finish.",
      viewAllHref: "#torriden-products",
      viewAllLabel: "View all",
      previousLabel: "Previous Torriden products",
      nextLabel: "Next Torriden products",
      products: [
        recommendation("torriden-serum", "db87c5c18e08c04278e4ea52fca49baa", "Torriden", "Dive In Low Molecule Hyaluronic Acid Serum, 1.7 fl oz", "$17.99", "$24.00", "19"),
        recommendation("torriden-cream", "3ccf61fd74fd43320d647a1b8779a978", "Torriden", "Dive In Low Molecular Hyaluronic Acid Soothing Cream, 3.38 fl oz", "$17.19", "$21.00", "11"),
        recommendation("torriden-pads", "d0e2ff743dbd793ce3bde737ca0d5915", "Torriden", "Dive In Low Molecular Hyaluronic Acid Multi Pad, 80pcs", "$16.59", "$26.00", "10"),
        recommendation("torriden-sun-serum", "7ff5c4a9f6e222d2f1339524bed0bd61", "Torriden", "Dive In Watery Sun Serum, 1.69 fl oz", "$14.99", "$29.00", "8"),
        recommendation("torriden-mask-value", "dffa7586c7799b674cc7a2024fba1bf4", "Torriden", "Dive In Low Molecule Hyaluronic Acid Mask, 20pcs", "$32.99", "$41.98", "2"),
        recommendation("torriden-cica-mask", "c89197762808c1b9d132550a33943908", "Torriden", "Balanceful Cica Facial Sheet Masks, 10pcs", "$17.29", "$29.99", "3"),
        recommendation("torriden-night-set", "f836e9292cf3db92609ae245f0eea8d3", "Torriden", "DIVE IN Low-Molecular Emergency Night Skincare Set", "$29.99", "$57.00", "1"),
        recommendation("torriden-toner", "a3c484049ff6976250c79c2bc9f5c65d", "Torriden", "Dive In Vegan Low Molecular Hyaluronic Acid Toner, 10.14 fl oz", "$15.49", "$19.99", "1"),
      ],
    },
    recentlyViewed: recentlyViewedProducts,
    copy: {
      galleryLabel: "Product image gallery",
      thumbnailsLabel: "Choose a product image",
      previousImage: "Previous product image",
      nextImage: "Next product image",
      openImagePreview: "Open image preview",
      closeImagePreview: "Close image preview",
      ratingLabel: "Rating",
      writeReview: "Write a review",
      bestBefore: "Best before",
      productHighlights: "Product highlights",
      specifications: "Specifications",
      disclaimer: "Disclaimer",
      disclaimerBody: "Product packaging, specifications, and price may change without notice. Always read the product label, warnings, and directions before use.",
      addToFavorites: "Add to favorites",
      share: "Share product",
      shareWeibo: "Share on Weibo",
      shareFacebook: "Share on Facebook",
      shareEmail: "Share by email",
      shareWechat: "Share on WeChat",
      getAffiliateLink: "Get Affiliate Link",
      quantity: "Quantity",
      decreaseQuantity: "Decrease quantity",
      increaseQuantity: "Increase quantity",
      addToCart: "Add to Cart",
      seller: "Sold & Shipped by Yami",
      shipTo: "Ship to",
      deliveryEstimate: "Get it tomorrow, Aug 21, if you order before 1:30 AM tomorrow.",
      serviceGuarantees: ["Free shipping over $49", "Ships from the United States", "Easy returns"],
      viewDetails: "View details",
      tags: "Tags",
      showAllTags: "Show all",
      showFewerTags: "Show fewer",
      recommendations: "Recommendations based on this item",
      recentlyViewed: "You've Recently Viewed",
      viewAll: "View all",
    },
  };

  if (locale === "en") return fixture;

  const reviewSection = fixture.reviewSection!;
  const reviewBodies = [
    "补水效果很好，使用感也很舒适。",
    "深层保湿，使用后肌肤感觉柔软水润。",
    "保湿感很明显，敷起来也很舒服。",
    "使用后皮肤更水润了，我会再次购买。",
    "步骤简单，补水效果很不错。",
    "适合干燥敏感肌，质地轻盈又保湿。",
    "膜布柔软，精华使用感舒适。",
    "膜布厚实，保湿但不会觉得厚重。",
    "方便加入日常护理，保湿且不黏腻。",
    "柔软舒缓，很适合每周补水护理。",
  ];
  const localizeProducts = (products: readonly ProductListItem[]) =>
    products.map((product) => ({
      ...product,
      soldCount:
        typeof product.soldCount === "string"
          ? product.soldCount.replace(/(\d+\+)\s+sold/i, "周销 $1")
          : product.soldCount,
      addButtonAriaLabel: `将 ${product.title} 加入购物车`,
    }));

  return {
    ...fixture,
    breadcrumb: [
      { label: "美妆护肤", href: "#beauty" },
      { label: "面膜", href: "#masks" },
      { label: "贴片面膜" },
    ],
    images: fixture.images.map((item, index) => ({
      ...item,
      alt: [
        "Torriden 低分子玻尿酸补水面膜正面包装",
        "Torriden 补水面膜包装与独立膜片",
        "Torriden 面膜膜布质地细节",
        "Torriden 面膜补水功效说明",
        "Torriden 面膜精华与上脸效果",
        "Torriden 面膜护肤步骤说明",
      ][index] ?? item.alt,
    })),
    title: "Torriden DIVE IN 低分子玻尿酸补水面膜 10片",
    ranking: "面膜人气榜 No.3",
    soldCount: "周销量 400+",
    discountLabel: "78折",
    optionGroups: [
      {
        ...fixture.optionGroups[0],
        label: "面膜类型",
        options: [
          { label: "粉色紧致款", value: "firming" },
          { label: "玻尿酸补水款", value: "hyaluronic" },
          { label: "积雪草舒缓款", value: "cica" },
        ],
      },
      {
        ...fixture.optionGroups[1],
        label: "规格",
        options: [
          { label: "4片/盒", value: "4-sheets" },
          { label: "5片装", value: "5-sheets" },
          { label: "10片装", value: "10-sheets" },
          { label: "20片装", value: "20-sheets" },
          { label: "3盒装", value: "3-packs" },
        ],
      },
    ],
    bestBefore: "2028年9月15日",
    highlights: [
      "蕴含 5D 玻尿酸复合成分，帮助多层补水。",
      "柔软纯素纤维膜布承载充足精华，贴合肌肤。",
      "轻盈精华易吸收，使用后清爽不黏腻。",
      "舒缓成分适合敏感肌，并帮助减轻紧绷感。",
      "敷用 15 分钟，肌肤水润柔软、富有光泽。",
    ],
    specifications: [
      { label: "品牌", value: "Torriden" },
      { label: "品牌产地", value: "韩国" },
      { label: "净含量", value: "1盒" },
      { label: "面膜类型", value: "玻尿酸补水" },
      { label: "包装规格", value: "10片" },
    ],
    purchaseTags: ["热销商品", "新品", "干燥", "油性肌", "干性肌"],
    region: {
      label: "地区",
      value: "韩国",
      iconSrc: koreaRegionIcon,
    },
    recommendations: localizeProducts(fixture.recommendations),
    recentlyViewed: localizeProducts(fixture.recentlyViewed ?? []),
    reviewSection: {
      ...reviewSection,
      title: "顾客评价",
      reviews: reviewSection.reviews.map((review, index) => ({
        ...review,
        locale: "评论于美国",
        verifiedPurchase: true,
        currentItem: true,
        variant: "面膜类型：玻尿酸补水款 · 包装规格：10片装",
        body: reviewBodies[index] ?? review.body,
      })),
      copy: {
        reviewsLabel: "条评价",
        referenceNotice: "部分评论来自其他选项，仅供参考。",
        writeReview: "写评价",
        all: "全部",
        purchased: "已购买",
        photos: "带图",
        reviewPhotos: "买家晒图",
        sortBy: "排序",
        viewMore: "查看全部评价",
        verifiedPurchase: "已验证购买",
        currentItem: "当前商品",
        showOriginal: "查看原文",
        helpful: "有帮助",
        comments: "评论",
        noReviews: "没有符合当前筛选条件的评价。",
        stars: "星",
        resetFilter: "查看全部评价",
      },
      sortOptions: reviewSection.sortOptions.map((option) => ({
        ...option,
        label: option.value === "recent" ? "最新评价" : "默认排序",
      })),
    },
    brandSection: fixture.brandSection
      ? {
          ...fixture.brandSection,
          aboutLabel: "品牌介绍",
          description:
            "Torriden 专注于清洁、纯素且无动物实验的高效补水配方。其代表性的 5D 低分子玻尿酸复合成分可提供分层保湿，同时保持清爽不黏腻。",
          viewAllLabel: "查看全部",
          previousLabel: "上一组 Torriden 商品",
          nextLabel: "下一组 Torriden 商品",
          products: localizeProducts(fixture.brandSection.products),
        }
      : undefined,
    copy: {
      galleryLabel: "商品图片",
      thumbnailsLabel: "选择商品图片",
      previousImage: "上一张商品图片",
      nextImage: "下一张商品图片",
      openImagePreview: "打开商品大图",
      closeImagePreview: "关闭商品大图",
      ratingLabel: "评分",
      writeReview: "写评价",
      bestBefore: "商品有效期至",
      productHighlights: "商品亮点",
      specifications: "商品规格",
      disclaimer: "免责声明",
      disclaimerBody:
        "商品包装、规格和价格可能随时调整。使用前请仔细阅读商品标签、警示和使用说明。",
      addToFavorites: "加入收藏",
      share: "分享商品",
      shareWeibo: "分享到微博",
      shareFacebook: "分享到 Facebook",
      shareEmail: "通过邮件分享",
      shareWechat: "分享到微信",
      getAffiliateLink: "获取推广链接",
      quantity: "数量",
      decreaseQuantity: "减少数量",
      increaseQuantity: "增加数量",
      addToCart: "加入购物车",
      optionSoldOut: "所有规格均无货",
      optionOtherCombination: "当前组合无货，选择后切换到有货规格",
      seller: "由亚米销售并发货",
      shipTo: "配送至",
      deliveryEstimate: "明天 1:30 AM 前下单，预计明天（8月28日 星期五）送达。",
      serviceGuarantees: ["满 $49 免运费", "从美国发货", "无忧退换"],
      viewDetails: "查看详情",
      tags: "标签",
      showAllTags: "展开全部",
      showFewerTags: "收起",
      recommendations: "基于此商品的推荐",
      recentlyViewed: "最近浏览",
      viewAll: "查看全部",
    },
  };
}
